"""woocommerce sync state: woo_synced_price, woo_sync_state

Revision ID: 2d0515b8dc93
Revises: 2d40d2364edc
Create Date: 2026-08-15 11:36:27.460454

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d0515b8dc93"
down_revision: str | Sequence[str] | None = "2d40d2364edc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "woo_sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seeded", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_seeded", sa.Integer(), nullable=False),
        sa.Column("last_created", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.Integer(), nullable=False),
        sa.Column("last_skipped", sa.Integer(), nullable=False),
        sa.Column("last_failed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "products", sa.Column("woo_synced_price", sa.Numeric(precision=14, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "woo_synced_price")
    op.drop_table("woo_sync_state")
    # ### end Alembic commands ###
