"""catalog tables: products, categories, material_centers, sync_state

Revision ID: 2d40d2364edc
Revises: 6155386a8342
Create Date: 2026-08-15 10:15:21.971734

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d40d2364edc"
down_revision: str | Sequence[str] | None = "6155386a8342"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("busy_group_name", sa.String(length=255), nullable=False),
        sa.Column("woo_category_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("busy_group_name"),
    )
    op.create_table(
        "material_centers",
        sa.Column("busy_code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=True),
        sa.Column("parent_group", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("busy_code"),
    )
    op.create_table(
        "sync_state",
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("last_stamp", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("entity"),
    )
    op.create_table(
        "products",
        sa.Column("busy_code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("item_group", sa.String(length=255), nullable=False),
        sa.Column("tracks_stock", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("woo_product_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_group"],
            ["categories.busy_group_name"],
        ),
        sa.PrimaryKeyConstraint("busy_code"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    op.drop_table("sync_state")
    op.drop_table("material_centers")
    op.drop_table("categories")
    # ### end Alembic commands ###
