"""add superadmin flag, sales_people table, product barcode

Revision ID: 75555db237c1
Revises: 86a947ed853f
Create Date: 2026-08-20 11:57:10.211236

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75555db237c1"
down_revision: str | Sequence[str] | None = "86a947ed853f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("material_center_code", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_center_code"],
            ["material_centers.busy_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("products", sa.Column("barcode", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "products", ["barcode"])
    op.add_column("users", sa.Column("is_superadmin", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superadmin")
    op.drop_constraint(None, "products", type_="unique")
    op.drop_column("products", "barcode")
    op.drop_table("sales_people")
    # ### end Alembic commands ###
