"""replace local sales_people table with BUSY-synced salesmen

Revision ID: c90dd2905fbc
Revises: 75555db237c1
Create Date: 2026-08-20 12:19:55.463277

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c90dd2905fbc"
down_revision: str | Sequence[str] | None = "75555db237c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesmen",
        sa.Column("busy_code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("alias", sa.String(length=64), nullable=True),
        sa.Column("parent_group", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("busy_code"),
    )
    op.drop_table("sales_people")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_people",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("full_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("material_center_code", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_active", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", mysql.DATETIME(), server_default=sa.text("(now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["material_center_code"],
            ["material_centers.busy_code"],
            name=op.f("sales_people_ibfk_1"),
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("salesmen")
    # ### end Alembic commands ###
